{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.flexapp.andr",
    "module": "flex-lib",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flex-lib-1.0.7.aar",
          "url": "flex-lib-1.0.7.aar",
          "size": 1939111,
          "sha512": "cc5dda94d306309567781b55c86a09ed29e522cdb473f0d0d796a361a59407e343bcb7a39ad8fb1b9da10c00079b6a08b8de452370624c11b1101c9f8977f2c2",
          "sha256": "01cce06d8c715431482fa7cdcac1ac6be1b7974b40ab4ec4398526764259ac57",
          "sha1": "63b40b658aeb8771f84cd67aed0752fcb7bb92bf",
          "md5": "025b5ccf992f90d02038c6aa2de44f65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-places",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "30.0.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-core"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-directboot"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "gifencoder-integration",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.google.apis",
          "module": "google-api-services-customsearch",
          "version": {
            "requires": "v1-rev59-1.23.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.altbeacon",
          "module": "android-beacon-library",
          "version": {
            "requires": "2.19.5-beta9"
          }
        },
        {
          "group": "com.github.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "flex-lib-1.0.7.aar",
          "url": "flex-lib-1.0.7.aar",
          "size": 1939111,
          "sha512": "cc5dda94d306309567781b55c86a09ed29e522cdb473f0d0d796a361a59407e343bcb7a39ad8fb1b9da10c00079b6a08b8de452370624c11b1101c9f8977f2c2",
          "sha256": "01cce06d8c715431482fa7cdcac1ac6be1b7974b40ab4ec4398526764259ac57",
          "sha1": "63b40b658aeb8771f84cd67aed0752fcb7bb92bf",
          "md5": "025b5ccf992f90d02038c6aa2de44f65"
        }
      ]
    }
  ]
}
