{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.flexapp.andr",
    "module": "flex-lib",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.1.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        }
      ],
      "files": [
        {
          "name": "flex-lib-1.0.14.aar",
          "url": "flex-lib-1.0.14.aar",
          "size": 1962510,
          "sha512": "3082b329f89a4e45d5029f0b0b29bfa5fa9d58ccf2aec70745c5b4b6c0e66a28d12913e0608902d6c33705b10170140c55c4558a1af78140d1dec70481811889",
          "sha256": "72975f5d86e1e7fef03da4213b86bd7b53c54c9df2ca3222b14664261341e2ca",
          "sha1": "80d8729635ba71376bade0f71b6362719dcf27ee",
          "md5": "69ca5b449e50d3d17e3c0c60fdfdba8f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-places",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-directboot"
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "gifencoder-integration",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.google.apis",
          "module": "google-api-services-customsearch",
          "version": {
            "requires": "v1-rev59-1.23.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.9"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.1.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        }
      ],
      "files": [
        {
          "name": "flex-lib-1.0.14.aar",
          "url": "flex-lib-1.0.14.aar",
          "size": 1962510,
          "sha512": "3082b329f89a4e45d5029f0b0b29bfa5fa9d58ccf2aec70745c5b4b6c0e66a28d12913e0608902d6c33705b10170140c55c4558a1af78140d1dec70481811889",
          "sha256": "72975f5d86e1e7fef03da4213b86bd7b53c54c9df2ca3222b14664261341e2ca",
          "sha1": "80d8729635ba71376bade0f71b6362719dcf27ee",
          "md5": "69ca5b449e50d3d17e3c0c60fdfdba8f"
        }
      ]
    }
  ]
}
